import { asc, eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { actionDebriefs, actions, actionServices, actionSuppliers, actionTypes, cities, serviceTypes, suppliers } from "../../drizzle/schema";
import { assertPermission } from "../authorization";
import { writeAuditLog } from "../audit";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";

async function requireDatabase() { const database = await getDb(); if (!database) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "Banco de dados indisponível." }); return database; }

export function canUpdateActionStatus(currentStatus: string, nextStatus: string) {
  return !["cancelled", "completed"].includes(currentStatus) && ["in_progress", "completed", "cancelled"].includes(nextStatus);
}

export const actionsRouter = router({
  referenceData: protectedProcedure.query(async ({ ctx }) => { await assertPermission(ctx.user, "actions.read"); const database = await requireDatabase(); const [cityRows, typeRows, supplierRows, serviceRows] = await Promise.all([database.select().from(cities).where(eq(cities.active, true)).orderBy(asc(cities.name)), database.select().from(actionTypes).where(eq(actionTypes.active, true)).orderBy(asc(actionTypes.name)), database.select().from(suppliers).where(eq(suppliers.active, true)).orderBy(asc(suppliers.displayName)), database.select().from(serviceTypes).where(eq(serviceTypes.active, true)).orderBy(asc(serviceTypes.name))]); return { cities: cityRows, actionTypes: typeRows, suppliers: supplierRows, serviceTypes: serviceRows }; }),
  list: protectedProcedure.query(async ({ ctx }) => { await assertPermission(ctx.user, "actions.read"); const database = await requireDatabase(); return database.select({ action: actions, cityName: cities.name, actionTypeName: actionTypes.name, debrief: actionDebriefs }).from(actions).innerJoin(cities, eq(actions.cityId, cities.id)).innerJoin(actionTypes, eq(actions.actionTypeId, actionTypes.id)).leftJoin(actionDebriefs, eq(actionDebriefs.actionId, actions.id)).orderBy(asc(actions.scheduledFor)); }),
  create: protectedProcedure.input(z.object({ cityId: z.number().int().positive(), actionTypeId: z.number().int().positive(), name: z.string().trim().min(2).max(180), address: z.string().trim().max(2000).optional(), latitude: z.number().min(-90).max(90).nullable(), longitude: z.number().min(-180).max(180).nullable(), scheduledFor: z.coerce.date(), objective: z.string().trim().min(3).max(2000), supplierIds: z.array(z.number().int().positive()).max(20), serviceTypeIds: z.array(z.number().int().positive()).max(20) })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "actions.write"); const database = await requireDatabase(); const created = await database.transaction(async transaction => { const [action] = await transaction.insert(actions).values({ cityId: input.cityId, actionTypeId: input.actionTypeId, name: input.name, address: input.address || null, latitude: input.latitude?.toFixed(7) ?? null, longitude: input.longitude?.toFixed(7) ?? null, scheduledFor: input.scheduledFor, objective: input.objective }).returning(); if (input.supplierIds.length) await transaction.insert(actionSuppliers).values(Array.from(new Set(input.supplierIds)).map(supplierId => ({ actionId: action.id, supplierId }))); if (input.serviceTypeIds.length) await transaction.insert(actionServices).values(Array.from(new Set(input.serviceTypeIds)).map(serviceTypeId => ({ actionId: action.id, serviceTypeId }))); return action; }); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "action", entityId: created.id, action: "create", afterData: created }); return created; }),
  updateExecutionStatus: protectedProcedure.input(z.object({ actionId: z.number().int().positive(), status: z.enum(["in_progress", "completed", "cancelled"]) })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "actions.write"); const database = await requireDatabase(); const [before] = await database.select().from(actions).where(eq(actions.id, input.actionId)).limit(1); if (!before) throw new TRPCError({ code: "NOT_FOUND", message: "Ação não encontrada." }); if (!canUpdateActionStatus(before.status, input.status)) throw new TRPCError({ code: "CONFLICT", message: "O status desta ação não pode mais ser alterado." }); const [updated] = await database.update(actions).set({ status: input.status, updatedAt: new Date() }).where(eq(actions.id, input.actionId)).returning(); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "action", entityId: updated.id, action: "update_execution_status", beforeData: before, afterData: updated }); return updated; }),
  saveDebrief: protectedProcedure.input(z.object({ actionId: z.number().int().positive(), rating: z.number().int().min(1).max(5), notes: z.string().trim().max(3000).optional(), positives: z.string().trim().max(2000).optional(), negatives: z.string().trim().max(2000).optional(), resultAchieved: z.boolean(), completedAt: z.coerce.date() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "actions.write"); const database = await requireDatabase(); const [current] = await database.select().from(actionDebriefs).where(eq(actionDebriefs.actionId, input.actionId)); const values = { ...input, notes: input.notes || null, positives: input.positives || null, negatives: input.negatives || null }; const [saved] = current ? await database.update(actionDebriefs).set(values).where(eq(actionDebriefs.actionId, input.actionId)).returning() : await database.insert(actionDebriefs).values(values).returning(); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "action_debrief", entityId: saved.id, action: current ? "update" : "create", afterData: saved }); return saved; }),
});
