import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { auditLogs, cities, documents, mediaCampaigns, mediaPoints, mediaTypes, regionals, serviceTypes, supplierCities, supplierMediaTypes, supplierServiceTypes, suppliers } from "../../drizzle/schema";
import { assertPermission } from "../authorization";
import { writeAuditLog } from "../audit";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";

async function requireDatabase() { const database = await getDb(); if (!database) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "Banco de dados indisponível." }); return database; }

const partnershipKinds = ["paid", "barter", "mixed"] as const;
const channelKinds = ["standard", "external"] as const;

function campaignStatusFor(startsOn: string) { return startsOn > new Date().toISOString().slice(0, 10) ? "scheduled" as const : "active" as const; }

async function assertPointRelationships(database: Awaited<ReturnType<typeof requireDatabase>>, input: { supplierId: number; cityId: number; mediaTypeId: number; serviceTypeId: number | null }) {
  const [supplier, city, cityCoverage, mediaCoverage, serviceCoverage] = await Promise.all([
    database.select().from(suppliers).where(and(eq(suppliers.id, input.supplierId), eq(suppliers.active, true))).limit(1),
    database.select().from(cities).where(and(eq(cities.id, input.cityId), eq(cities.active, true))).limit(1),
    database.select().from(supplierCities).where(and(eq(supplierCities.supplierId, input.supplierId), eq(supplierCities.cityId, input.cityId))).limit(1),
    database.select().from(supplierMediaTypes).where(and(eq(supplierMediaTypes.supplierId, input.supplierId), eq(supplierMediaTypes.mediaTypeId, input.mediaTypeId))).limit(1),
    input.serviceTypeId ? database.select().from(supplierServiceTypes).where(and(eq(supplierServiceTypes.supplierId, input.supplierId), eq(supplierServiceTypes.serviceTypeId, input.serviceTypeId))).limit(1) : Promise.resolve([]),
  ]);
  if (!supplier[0]) throw new TRPCError({ code: "BAD_REQUEST", message: "Selecione um fornecedor ativo." });
  if (!city[0]) throw new TRPCError({ code: "BAD_REQUEST", message: "Selecione uma cidade ativa." });
  if (!cityCoverage[0]) throw new TRPCError({ code: "BAD_REQUEST", message: "O fornecedor não está habilitado para atender a cidade selecionada. Atualize a cobertura do fornecedor." });
  if (!mediaCoverage[0]) throw new TRPCError({ code: "BAD_REQUEST", message: "O fornecedor não está habilitado para este tipo de mídia. Atualize sua cobertura." });
  if (input.serviceTypeId && !serviceCoverage[0]) throw new TRPCError({ code: "BAD_REQUEST", message: "O fornecedor não está habilitado para o serviço selecionado. Atualize sua cobertura." });
}

export const mediaRouter = router({
  referenceData: protectedProcedure.query(async ({ ctx }) => { await assertPermission(ctx.user, "media.read"); const database = await requireDatabase(); const [supplierRows, cityRows, regionalRows, mediaTypeRows, serviceRows] = await Promise.all([database.select().from(suppliers).where(eq(suppliers.active, true)).orderBy(asc(suppliers.displayName)), database.select({ city: cities, regionalName: regionals.name }).from(cities).innerJoin(regionals, eq(cities.regionalId, regionals.id)).where(eq(cities.active, true)).orderBy(asc(cities.name)), database.select().from(regionals).where(eq(regionals.active, true)).orderBy(asc(regionals.name)), database.select().from(mediaTypes).where(eq(mediaTypes.active, true)).orderBy(asc(mediaTypes.name)), database.select().from(serviceTypes).where(eq(serviceTypes.active, true)).orderBy(asc(serviceTypes.name))]); return { suppliers: supplierRows, cities: cityRows, regionals: regionalRows, mediaTypes: mediaTypeRows, serviceTypes: serviceRows }; }),
  list: protectedProcedure.input(z.object({ regionalId: z.number().int().positive().optional(), cityId: z.number().int().positive().optional(), channelKind: z.enum(channelKinds).optional(), status: z.enum(["active", "scheduled", "completed", "cancelled"]).optional(), partnershipType: z.enum(partnershipKinds).optional() }).optional()).query(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.read"); const database = await requireDatabase(); const conditions = []; if (input?.regionalId) conditions.push(eq(cities.regionalId, input.regionalId)); if (input?.cityId) conditions.push(eq(mediaPoints.cityId, input.cityId)); if (input?.channelKind) conditions.push(eq(mediaPoints.channelKind, input.channelKind)); const [points, campaigns] = await Promise.all([database.select({ point: mediaPoints, supplierName: suppliers.displayName, cityName: cities.name, regionalId: cities.regionalId, regionalName: regionals.name, mediaTypeName: mediaTypes.name, serviceTypeName: serviceTypes.name }).from(mediaPoints).innerJoin(suppliers, eq(mediaPoints.supplierId, suppliers.id)).innerJoin(cities, eq(mediaPoints.cityId, cities.id)).innerJoin(regionals, eq(cities.regionalId, regionals.id)).innerJoin(mediaTypes, eq(mediaPoints.mediaTypeId, mediaTypes.id)).leftJoin(serviceTypes, eq(mediaPoints.serviceTypeId, serviceTypes.id)).where(conditions.length ? and(...conditions) : undefined).orderBy(asc(mediaPoints.name)), database.select().from(mediaCampaigns).orderBy(desc(mediaCampaigns.startsOn))]); return points.map(({ point, ...labels }) => { const pointCampaigns = campaigns.filter(campaign => campaign.mediaPointId === point.id && (!input?.status || campaign.status === input.status) && (!input?.partnershipType || campaign.partnershipType === input.partnershipType)); return { ...point, ...labels, campaigns: pointCampaigns, activeCampaign: pointCampaigns.find(campaign => campaign.status === "active") ?? null, nextCampaign: pointCampaigns.find(campaign => campaign.status === "scheduled") ?? null }; }).filter(point => !input?.status && !input?.partnershipType || point.campaigns.length > 0); }),
  pointDetails: protectedProcedure.input(z.object({ mediaPointId: z.number().int().positive() })).query(async ({ ctx, input }) => {
    await assertPermission(ctx.user, "media.read");
    const database = await requireDatabase();
    const [row] = await database.select({ point: mediaPoints, supplierName: suppliers.displayName, cityName: cities.name, regionalId: cities.regionalId, regionalName: regionals.name, mediaTypeName: mediaTypes.name, serviceTypeName: serviceTypes.name }).from(mediaPoints).innerJoin(suppliers, eq(mediaPoints.supplierId, suppliers.id)).innerJoin(cities, eq(mediaPoints.cityId, cities.id)).innerJoin(regionals, eq(cities.regionalId, regionals.id)).innerJoin(mediaTypes, eq(mediaPoints.mediaTypeId, mediaTypes.id)).leftJoin(serviceTypes, eq(mediaPoints.serviceTypeId, serviceTypes.id)).where(eq(mediaPoints.id, input.mediaPointId)).limit(1);
    if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Ponto de mídia não encontrado." });
    const campaigns = await database.select().from(mediaCampaigns).where(eq(mediaCampaigns.mediaPointId, input.mediaPointId)).orderBy(desc(mediaCampaigns.startsOn));
    const campaignIds = campaigns.map(campaign => campaign.id);
    const [pointHistory, campaignHistory, evidences] = await Promise.all([
      database.select().from(auditLogs).where(and(eq(auditLogs.entityType, "media_point"), eq(auditLogs.entityId, input.mediaPointId))).orderBy(desc(auditLogs.occurredAt)),
      campaignIds.length ? database.select().from(auditLogs).where(and(eq(auditLogs.entityType, "media_campaign"), inArray(auditLogs.entityId, campaignIds))).orderBy(desc(auditLogs.occurredAt)) : Promise.resolve([]),
      campaignIds.length ? database.select().from(documents).where(and(eq(documents.entityType, "media_campaign"), inArray(documents.entityId, campaignIds))).orderBy(desc(documents.createdAt)) : Promise.resolve([]),
    ]);
    return { ...row.point, supplierName: row.supplierName, cityName: row.cityName, regionalId: row.regionalId, regionalName: row.regionalName, mediaTypeName: row.mediaTypeName, serviceTypeName: row.serviceTypeName, campaigns: campaigns.map(campaign => ({ ...campaign, evidences: evidences.filter(document => document.entityId === campaign.id) })), history: [...pointHistory.map(item => ({ ...item, scope: "point" as const })), ...campaignHistory.map(item => ({ ...item, scope: "campaign" as const }))].sort((first, second) => second.occurredAt.getTime() - first.occurredAt.getTime()) };
  }),
  createPoint: protectedProcedure.input(z.object({ supplierId: z.number().int().positive(), cityId: z.number().int().positive(), mediaTypeId: z.number().int().positive(), serviceTypeId: z.number().int().positive().nullable(), name: z.string().trim().min(2).max(180), channelKind: z.enum(channelKinds).default("standard"), address: z.string().trim().max(2000).optional(), latitude: z.number().min(-90).max(90).nullable(), longitude: z.number().min(-180).max(180).nullable() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.write"); const database = await requireDatabase(); await assertPointRelationships(database, input); const [created] = await database.insert(mediaPoints).values({ ...input, address: input.address || null, latitude: input.latitude?.toFixed(7) ?? null, longitude: input.longitude?.toFixed(7) ?? null }).returning(); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "media_point", entityId: created.id, action: "create", afterData: created }); return created; }),
  createCampaign: protectedProcedure.input(z.object({ mediaPointId: z.number().int().positive(), name: z.string().trim().min(2).max(180), startsOn: z.string().date(), endsOn: z.string().date(), partnershipType: z.enum(partnershipKinds).default("paid"), estimatedCost: z.number().min(0).default(0), notes: z.string().trim().max(2000).optional(), campaignDetails: z.string().trim().max(4000).optional() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.write"); if (input.endsOn < input.startsOn) throw new TRPCError({ code: "BAD_REQUEST", message: "A data de término deve ser posterior à data de início." }); const database = await requireDatabase(); const status = campaignStatusFor(input.startsOn); if (status === "active") { const [existing] = await database.select({ id: mediaCampaigns.id }).from(mediaCampaigns).where(and(eq(mediaCampaigns.mediaPointId, input.mediaPointId), eq(mediaCampaigns.status, "active"))); if (existing) throw new TRPCError({ code: "CONFLICT", message: "Este ponto já possui uma campanha ativa. Agende a próxima campanha ou reagende a atual." }); } const [created] = await database.insert(mediaCampaigns).values({ ...input, estimatedCost: input.estimatedCost.toFixed(2), notes: input.notes || null, campaignDetails: input.campaignDetails || null, status }).returning(); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "media_campaign", entityId: created.id, action: status === "scheduled" ? "schedule" : "create", afterData: created }); return created; }),
  renewCampaign: protectedProcedure.input(z.object({ sourceCampaignId: z.number().int().positive(), name: z.string().trim().min(2).max(180), startsOn: z.string().date(), endsOn: z.string().date(), partnershipType: z.enum(partnershipKinds).default("paid"), estimatedCost: z.number().min(0).default(0), notes: z.string().trim().max(2000).optional(), campaignDetails: z.string().trim().max(4000).optional(), rescheduleReason: z.string().trim().min(3).max(2000).optional() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.write"); if (input.endsOn < input.startsOn) throw new TRPCError({ code: "BAD_REQUEST", message: "A vigência do reagendamento é inválida." }); const database = await requireDatabase(); const result = await database.transaction(async transaction => { const [source] = await transaction.select().from(mediaCampaigns).where(eq(mediaCampaigns.id, input.sourceCampaignId)).limit(1); if (!source) throw new TRPCError({ code: "NOT_FOUND", message: "Campanha de origem não encontrada." }); if (!["active", "scheduled"].includes(source.status)) throw new TRPCError({ code: "CONFLICT", message: "Apenas campanhas ativas ou agendadas podem ser reagendadas." }); if (input.startsOn < source.endsOn) throw new TRPCError({ code: "BAD_REQUEST", message: "A nova campanha deve iniciar no encerramento ou após a vigência atual." }); await transaction.update(mediaCampaigns).set({ status: source.status === "active" ? "completed" : "cancelled", updatedAt: new Date() }).where(eq(mediaCampaigns.id, source.id)); const [created] = await transaction.insert(mediaCampaigns).values({ mediaPointId: source.mediaPointId, name: input.name, startsOn: input.startsOn, endsOn: input.endsOn, partnershipType: input.partnershipType, estimatedCost: input.estimatedCost.toFixed(2), notes: input.notes || null, campaignDetails: input.campaignDetails || null, rescheduleReason: input.rescheduleReason || "Reagendamento de campanha", rescheduledFromCampaignId: source.id, status: campaignStatusFor(input.startsOn) }).returning(); return { source, created }; }); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "media_campaign", entityId: result.created.id, action: "reschedule", beforeData: result.source, afterData: result.created }); return result.created; }),
  saveDebrief: protectedProcedure.input(z.object({ campaignId: z.number().int().positive(), rating: z.number().int().min(1).max(5), resultAchieved: z.boolean(), feedback: z.string().trim().min(3).max(4000) })).mutation(async ({ ctx, input }) => {
    await assertPermission(ctx.user, "media.write");
    const database = await requireDatabase();
    const [before] = await database.select().from(mediaCampaigns).where(eq(mediaCampaigns.id, input.campaignId)).limit(1);
    if (!before) throw new TRPCError({ code: "NOT_FOUND", message: "Campanha não encontrada." });
    const [saved] = await database.update(mediaCampaigns).set({ rating: input.rating, resultAchieved: input.resultAchieved, feedback: input.feedback, updatedAt: new Date() }).where(eq(mediaCampaigns.id, input.campaignId)).returning();
    await writeAuditLog({ actorUserId: ctx.user.id, entityType: "media_campaign", entityId: saved.id, action: "save_debrief", beforeData: before, afterData: saved });
    return saved;
  }),
});
