import { and, asc, eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { cities, mediaCampaigns, mediaPoints, mediaTypes, regionals, serviceTypes, suppliers } from "../../drizzle/schema";
import { assertPermission } from "../authorization";
import { writeAuditLog } from "../audit";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";

async function requireDatabase() { const database = await getDb(); if (!database) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "Banco de dados indisponível." }); return database; }

export const mediaRouter = router({
  referenceData: protectedProcedure.query(async ({ ctx }) => { await assertPermission(ctx.user, "media.read"); const database = await requireDatabase(); const [supplierRows, cityRows, regionalRows, mediaTypeRows, serviceRows] = await Promise.all([database.select().from(suppliers).where(eq(suppliers.active, true)).orderBy(asc(suppliers.displayName)), database.select({ city: cities, regionalName: regionals.name }).from(cities).innerJoin(regionals, eq(cities.regionalId, regionals.id)).where(eq(cities.active, true)).orderBy(asc(cities.name)), database.select().from(regionals).where(eq(regionals.active, true)).orderBy(asc(regionals.name)), database.select().from(mediaTypes).where(eq(mediaTypes.active, true)).orderBy(asc(mediaTypes.name)), database.select().from(serviceTypes).where(eq(serviceTypes.active, true)).orderBy(asc(serviceTypes.name))]); return { suppliers: supplierRows, cities: cityRows, regionals: regionalRows, mediaTypes: mediaTypeRows, serviceTypes: serviceRows }; }),
  list: protectedProcedure.input(z.object({ regionalId: z.number().int().positive().optional(), cityId: z.number().int().positive().optional() }).optional()).query(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.read"); const database = await requireDatabase(); const conditions = []; if (input?.regionalId) conditions.push(eq(cities.regionalId, input.regionalId)); if (input?.cityId) conditions.push(eq(mediaPoints.cityId, input.cityId)); const [points, campaigns] = await Promise.all([database.select({ point: mediaPoints, supplierName: suppliers.displayName, cityName: cities.name, regionalId: cities.regionalId, regionalName: regionals.name, mediaTypeName: mediaTypes.name, serviceTypeName: serviceTypes.name }).from(mediaPoints).innerJoin(suppliers, eq(mediaPoints.supplierId, suppliers.id)).innerJoin(cities, eq(mediaPoints.cityId, cities.id)).innerJoin(regionals, eq(cities.regionalId, regionals.id)).innerJoin(mediaTypes, eq(mediaPoints.mediaTypeId, mediaTypes.id)).leftJoin(serviceTypes, eq(mediaPoints.serviceTypeId, serviceTypes.id)).where(conditions.length ? and(...conditions) : undefined).orderBy(asc(mediaPoints.name)), database.select().from(mediaCampaigns).orderBy(asc(mediaCampaigns.endsOn))]); return points.map(({ point, ...labels }) => ({ ...point, ...labels, campaigns: campaigns.filter(campaign => campaign.mediaPointId === point.id), activeCampaign: campaigns.find(campaign => campaign.mediaPointId === point.id && campaign.status === "active") ?? null })); }),
  createPoint: protectedProcedure.input(z.object({ supplierId: z.number().int().positive(), cityId: z.number().int().positive(), mediaTypeId: z.number().int().positive(), serviceTypeId: z.number().int().positive().nullable(), name: z.string().trim().min(2).max(180), address: z.string().trim().max(2000).optional(), latitude: z.number().min(-90).max(90).nullable(), longitude: z.number().min(-180).max(180).nullable() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.write"); const database = await requireDatabase(); const [created] = await database.insert(mediaPoints).values({ ...input, serviceTypeId: input.serviceTypeId, address: input.address || null, latitude: input.latitude?.toFixed(7) ?? null, longitude: input.longitude?.toFixed(7) ?? null }).returning(); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "media_point", entityId: created.id, action: "create", afterData: created }); return created; }),
  createCampaign: protectedProcedure.input(z.object({ mediaPointId: z.number().int().positive(), name: z.string().trim().min(2).max(180), startsOn: z.string().date(), endsOn: z.string().date(), notes: z.string().trim().max(2000).optional() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.write"); if (input.endsOn < input.startsOn) throw new TRPCError({ code: "BAD_REQUEST", message: "A data de término deve ser posterior à data de início." }); const database = await requireDatabase(); const [existing] = await database.select({ id: mediaCampaigns.id }).from(mediaCampaigns).where(and(eq(mediaCampaigns.mediaPointId, input.mediaPointId), eq(mediaCampaigns.status, "active"))); if (existing) throw new TRPCError({ code: "CONFLICT", message: "Este ponto de mídia já possui uma campanha ativa." }); const [created] = await database.insert(mediaCampaigns).values({ ...input, notes: input.notes || null, status: "active" }).returning(); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "media_campaign", entityId: created.id, action: "create", afterData: created }); return created; }),
  renewCampaign: protectedProcedure.input(z.object({ sourceCampaignId: z.number().int().positive(), name: z.string().trim().min(2).max(180), startsOn: z.string().date(), endsOn: z.string().date(), notes: z.string().trim().max(2000).optional() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user, "media.write"); if (input.endsOn < input.startsOn) throw new TRPCError({ code: "BAD_REQUEST", message: "A vigência de renovação é inválida." }); const database = await requireDatabase(); const result = await database.transaction(async transaction => { const [source] = await transaction.select().from(mediaCampaigns).where(eq(mediaCampaigns.id, input.sourceCampaignId)).limit(1); if (!source) throw new TRPCError({ code: "NOT_FOUND", message: "Campanha de origem não encontrada." }); if (source.status !== "active") throw new TRPCError({ code: "CONFLICT", message: "Apenas campanhas ativas podem ser renovadas." }); if (input.startsOn < source.endsOn) throw new TRPCError({ code: "BAD_REQUEST", message: "A renovação deve começar no encerramento ou após a vigência atual." }); await transaction.update(mediaCampaigns).set({ status: "completed", updatedAt: new Date() }).where(eq(mediaCampaigns.id, source.id)); const [created] = await transaction.insert(mediaCampaigns).values({ mediaPointId: source.mediaPointId, name: input.name, startsOn: input.startsOn, endsOn: input.endsOn, notes: input.notes || null, status: "active" }).returning(); return { source, created }; }); await writeAuditLog({ actorUserId: ctx.user.id, entityType: "media_campaign", entityId: result.created.id, action: "renew", beforeData: result.source, afterData: result.created }); return result.created; }),
});
