import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { BarChart3, BookOpenCheck, Boxes, CalendarDays, CircleHelp, Landmark, Mail, MapPinned, Megaphone, Send, Settings2, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const guides = [
  { title: "Ações e eventos", description: "Planeje, atribua responsáveis, registre fornecedores, evidências e o debriefing de cada ativação.", icon: CalendarDays },
  { title: "Mídias", description: "Cadastre pontos e campanhas, controle vigências e mantenha evidências de veiculação acessíveis.", icon: Megaphone },
  { title: "Estoque", description: "Controle materiais por cidade, registre transferências e acompanhe saldos mínimos.", icon: Boxes },
  { title: "Financeiro", description: "Acompanhe orçamento, custos, notas fiscais, pagamentos e seus vínculos operacionais.", icon: Landmark },
  { title: "Indicadores", description: "Use filtros territoriais e o mapa operacional para acompanhar cobertura e desempenho.", icon: BarChart3 },
  { title: "Cadastros e acessos", description: "Administre territórios, fornecedores, ofertas, tipos operacionais, contas e permissões conforme seu papel.", icon: Settings2 },
];

const documentationSections = [
  { value: "inicio", title: "Comece pelo fluxo certo", content: <ol className="list-decimal space-y-2 pl-5"><li>Acesse <strong>Cadastros</strong> e valide empresas, regionais, cidades, fornecedores, serviços e tipos necessários.</li><li>Use os módulos de <strong>Operação</strong> para registrar ações, mídias e eventos com os dados do planejamento.</li><li>Acompanhe materiais e custos em <strong>Gestão</strong> e finalize com evidências, debriefing e indicadores.</li></ol> },
  { value: "acesso", title: "Acesso, perfis e permissões", content: <><p>O administrador define papéis, responsabilidades territoriais e permissões específicas em <strong>Cadastros → Usuários e permissões</strong>. As permissões individuais têm precedência sobre o papel quando configuradas.</p><p className="mt-2">Contas locais usam senha própria; contas institucionais utilizam a autenticação OAuth. Nunca compartilhe credenciais e encerre a sessão em equipamentos compartilhados.</p></> },
  { value: "cadastros", title: "Cadastros operacionais", content: <ol className="list-decimal space-y-2 pl-5"><li>Cadastre a empresa de faturamento, CNPJ e contatos responsáveis.</li><li>Crie regionais e cidades com endereço, CEP e localização; mantenha a cobertura territorial atualizada.</li><li>Inclua fornecedores, parceiros, ofertas, preços, serviços, supervisores comerciais e tipos operacionais, sempre verificando o status ativo.</li><li>Evite apagar registros usados: prefira inativá-los para preservar histórico e relatórios.</li></ol> },
  { value: "acoes", title: "Ações de trade", content: <ol className="list-decimal space-y-2 pl-5"><li>Abra uma ação e preencha objetivo, território, datas e responsáveis.</li><li>Associe fornecedores e serviços, registre custos previstos e defina os materiais que serão separados do estoque quando o fluxo estiver disponível.</li><li>Durante a execução, mantenha o status atualizado e anexe evidências autorizadas.</li><li>Finalize com debriefing, avaliação de resultado e aprendizados para próximas ativações.</li></ol> },
  { value: "eventos", title: "Eventos e parcerias", content: <ol className="list-decimal space-y-2 pl-5"><li>Registre data, local, objetivos e as entregas esperadas no pré-evento.</li><li>Informe modalidade da parceria, fornecedores, serviços, recursos operacionais e custo previsto quando aplicável.</li><li>Ao encerrar, documente evidências, avaliação de 1 a 5, pontos de melhoria e a decisão sobre renovar a parceria.</li></ol> },
  { value: "midias", title: "Mídias e campanhas", content: <ol className="list-decimal space-y-2 pl-5"><li>Cadastre o ponto de mídia com tipo, localização, cidade, regional e fornecedor responsável.</li><li>Crie a campanha com vigência, investimento e status; uma única campanha ativa é mantida por ponto conforme a regra do sistema.</li><li>Anexe comprovações de veiculação e acompanhe renovações, alterações e cobertura por território.</li></ol> },
  { value: "estoque", title: "Estoque de materiais", content: <ol className="list-decimal space-y-2 pl-5"><li>Cadastre cada item com SKU, categoria, unidade e estoque mínimo.</li><li>Registre entradas, saídas, ajustes e transferências entre cidades; cada movimento fica rastreável no histórico.</li><li>Consulte os saldos por regional e cidade antes de planejar uma ativação e acompanhe alertas de nível mínimo.</li></ol> },
  { value: "financeiro", title: "Financeiro, notas e pagamentos", content: <ol className="list-decimal space-y-2 pl-5"><li>Configure categorias financeiras e crie o orçamento mensal por verba.</li><li>Registre custos com fornecedor, vencimento e referência operacional; submeta à aprovação quando aplicável.</li><li>Anexe notas fiscais e comprovantes, acompanhe pagamentos e use os filtros para conferir competência, fornecedor e status.</li></ol> },
  { value: "indicadores", title: "BI e indicadores", content: <><p>Use a área de indicadores para comparar desempenho de fornecedores, custos, operações e cobertura territorial. Aplique filtros antes de interpretar os números e trate dados sem evidência como pendentes de validação.</p><p className="mt-2">O mapa consolida mídias, ações e eventos registrados; mantenha coordenadas dos cadastros de cidades atualizadas para uma leitura territorial confiável.</p></> },
  { value: "suporte", title: "Suporte e boas práticas", content: <><p>Antes de solicitar ajuda, reúna o módulo afetado, cidade e regional, horário, passo executado e uma descrição do resultado esperado. Não inclua senhas ou dados sensíveis na mensagem.</p><p className="mt-2">Use o formulário desta página para preparar o contato com o suporte. Para alterações de acesso, procure uma pessoa administradora do Trade HUB.</p></> },
];

export default function HelpWorkspace() {
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!subject.trim() || !message.trim()) return toast.error("Informe o assunto e descreva como podemos ajudar.");
    const body = `Solicitação enviada pelo Trade HUB — Cluster MG\n\nAssunto: ${subject.trim()}\n\nDescrição:\n${message.trim()}`;
    window.location.href = `mailto:suporte@hubtrade.app?subject=${encodeURIComponent(`[Trade HUB] ${subject.trim()}`)}&body=${encodeURIComponent(body)}`;
    toast.success("Seu aplicativo de e-mail foi preparado para enviar a solicitação.");
  };

  return <div className="mx-auto max-w-6xl">
    <header className="flex gap-4 border-b border-border pb-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-primary text-white shadow-sm"><CircleHelp className="h-5 w-5" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground">Central de conhecimento</p><h1 className="mt-1 font-display text-3xl font-semibold tracking-tight text-foreground">Ajuda e suporte</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Consulte os fluxos do Trade HUB ou envie uma solicitação com o máximo de contexto possível para agilizar o atendimento.</p></div></header>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]">
      <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4 text-primary" /><h2 className="font-display text-lg font-semibold text-foreground">Como utilizar o sistema</h2></div><p className="mt-1 text-sm leading-6 text-muted-foreground">Os cadastros sustentam a operação. Primeiro, mantenha empresas, territórios, fornecedores e tipos atualizados em <strong>Cadastros</strong>; depois registre ações, mídias ou eventos e acompanhe materiais e custos pelos módulos de Gestão.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{guides.map(guide => { const Icon = guide.icon; return <article key={guide.title} className="rounded-xl border border-border bg-secondary/40 p-4"><Icon className="h-4 w-4 text-primary" /><h3 className="mt-3 font-semibold text-foreground">{guide.title}</h3><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{guide.description}</p></article>; })}</div><div className="mt-5 rounded-xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-foreground"><ShieldCheck className="h-4 w-4 text-primary" /> Boas práticas de segurança</div><p className="mt-1.5 text-xs leading-5 text-muted-foreground">Use apenas sua conta, encerre a sessão em dispositivos compartilhados e solicite a um administrador qualquer ajuste de acesso ou permissão.</p></div><div className="mt-7 border-t border-border pt-5"><h2 className="font-display text-lg font-semibold text-foreground">Documentação completa</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Abra cada tópico para consultar os passos e regras de operação do Trade HUB.</p><Accordion type="single" collapsible className="mt-3 w-full">{documentationSections.map(section => <AccordionItem key={section.value} value={section.value}><AccordionTrigger className="text-left text-sm font-semibold text-foreground hover:no-underline">{section.title}</AccordionTrigger><AccordionContent className="text-xs leading-5 text-muted-foreground">{section.content}</AccordionContent></AccordionItem>)}</Accordion></div></section>
      <form onSubmit={submit} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Mail className="h-4 w-4 text-primary" /><h2 className="font-display text-lg font-semibold text-foreground">Solicitar ajuda</h2></div><p className="mt-1 text-sm leading-6 text-muted-foreground">Ao enviar, será aberto um e-mail já preenchido para a equipe de suporte.</p><div className="mt-5 space-y-4"><div><Label htmlFor="help-subject">Assunto</Label><Input id="help-subject" value={subject} onChange={event => setSubject(event.target.value)} maxLength={160} placeholder="Ex.: Dúvida sobre lançamento financeiro" className="mt-1.5" /></div><div><Label htmlFor="help-message">Descreva a solicitação</Label><Textarea id="help-message" value={message} onChange={event => setMessage(event.target.value)} maxLength={3000} placeholder="Informe o módulo, o que você estava tentando fazer e o resultado esperado." className="mt-1.5 min-h-40 resize-y" /></div></div><Button type="submit" className="mt-6 w-full bg-primary hover:bg-primary/90"><Send className="mr-1.5 h-4 w-4" /> Preparar solicitação</Button><p className="mt-3 text-center text-[11px] leading-5 text-muted-foreground">Para demandas urgentes, inclua cidade, regional e horário da ocorrência.</p></form>
    </div>
  </div>;
}
