import EvidenceUpload from "@/components/EvidenceUpload";
import SearchableMultiSelect from "@/components/SearchableMultiSelect";
import { OperationalDebriefing, OperationalHistory, OperationalStatusDialog, OperationalStatusDropdown, createEmptyOperationalDebrief, resolveHistoryEvidence, type OperationalDebriefValue, type OperationalStatusOption } from "@/components/OperationalPatterns";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useEffectivePermissions } from "@/hooks/useEffectivePermissions";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CalendarClock, CalendarDays, FileAudio, History, MapPin, Pencil, RefreshCw, Signal, UsersRound, Volume2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";
import ContextTaskDialog from "@/components/ContextTaskDialog";

type CampaignStatus = "scheduled" | "active" | "inactive" | "completed" | "cancelled";
type PartnershipType = "paid" | "barter" | "mixed";

const statusLabels: Record<CampaignStatus, string> = { scheduled: "Agendada", active: "Ativa", inactive: "Inativa", completed: "Encerrada", cancelled: "Cancelada" };
const statusOptions: OperationalStatusOption<CampaignStatus>[] = [{ value: "scheduled", label: "Agendada" }, { value: "active", label: "Ativa" }, { value: "inactive", label: "Inativa" }, { value: "completed", label: "Encerrada" }, { value: "cancelled", label: "Cancelada" }];
const partnershipLabels: Record<PartnershipType, string> = { paid: "Pago", barter: "Permuta", mixed: "Misto" };

function formatDate(value: string | null | undefined) { return value ? new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("pt-BR") : "Não informado"; }
function formatDateTime(value: string | Date | null | undefined) { return value ? new Date(value).toLocaleString("pt-BR") : "Não informado"; }

export default function MidiaVolanteVeiculacaoPage() {
  const [, params] = useRoute("/midias/volante/veiculacao/:campaignId");
  const [, setLocation] = useLocation();
  const { can } = useEffectivePermissions();
  const canWrite = can("media.write");
  const campaignId = Number(params?.campaignId ?? 0);
  const utils = trpc.useUtils();
  const detail = trpc.media.campaignDetails.useQuery({ campaignId }, { enabled: campaignId > 0 });
  const references = trpc.media.referenceData.useQuery();
  const tradeCampaigns = trpc.campaigns.list.useQuery();
  const [statusDialog, setStatusDialog] = useState(false);
  const [pendingStatus, setPendingStatus] = useState<CampaignStatus>("active");
  const [statusReason, setStatusReason] = useState("");
  const [statusEvidenceIds, setStatusEvidenceIds] = useState<number[]>([]);
  const [rescheduleOpen, setRescheduleOpen] = useState(false);
  const [rescheduleReason, setRescheduleReason] = useState("");
  const [rescheduleDates, setRescheduleDates] = useState({ startsOn: "", endsOn: "" });
  const [editOpen, setEditOpen] = useState(false);
  const [editForm, setEditForm] = useState({ name: "", startsOn: "", endsOn: "", serviceTypeId: "", tradeCampaignId: "", responsibleUserId: "", campaignDetails: "" });
  const [debrief, setDebrief] = useState<OperationalDebriefValue>(createEmptyOperationalDebrief());
  const campaign = detail.data;
  const point = campaign?.point;
  const historyDocuments = useMemo(() => campaign?.historyEvidences ?? [], [campaign?.historyEvidences]);
  const serviceOptions = useMemo(() => (references.data?.serviceTypes ?? []).map(service => ({ id: service.id, label: service.name ?? `Serviço ${service.id}`, description: "Serviço operacional mídia volante" })), [references.data?.serviceTypes]);
  const campaignOptions = useMemo(() => (tradeCampaigns.data ?? []).map(row => ({ id: row.id, label: row.name, description: "Campanha vinculada" })), [tradeCampaigns.data]);
  const responsibleOptions = useMemo(() => (references.data?.users ?? []).map(user => ({ id: user.id, label: user.name ?? `Usuário ${user.id}`, description: user.jobTitle || user.email || undefined })), [references.data?.users]);

  useEffect(() => {
    if (!campaign) return;
    setDebrief({ rating: campaign.rating ? String(campaign.rating) : "", resultSummary: campaign.debriefHistory ?? campaign.feedback ?? "", notes: campaign.debriefResult ?? campaign.debriefEvaluation ?? "", leadCount: "0", saleCount: "0", renewalCount: "0", positives: campaign.debriefEvaluation ?? "", negatives: campaign.debriefLearnings ?? "", resultAchieved: campaign.resultAchieved ?? true, worthRepeating: true, completedAt: campaign.debriefAt ? new Date(campaign.debriefAt).toISOString().slice(0, 16) : new Date().toISOString().slice(0, 16) });
    setRescheduleDates({ startsOn: campaign.startsOn.slice(0, 10), endsOn: campaign.endsOn.slice(0, 10) });
  }, [campaign]);

  const refresh = () => { void utils.media.campaignDetails.invalidate({ campaignId }); void utils.media.pointDetails.invalidate({ mediaPointId: point?.id }); void utils.media.list.invalidate(); };
  const updateStatus = trpc.media.updateCampaignStatus.useMutation({ onSuccess: () => { toast.success("Status da veiculação atualizado."); setStatusDialog(false); setStatusReason(""); setStatusEvidenceIds([]); refresh(); }, onError: error => toast.error(error.message) });
  const renew = trpc.media.renewCampaign.useMutation({ onSuccess: () => { toast.success("Veiculação reagendada sem duplicação."); setRescheduleOpen(false); setRescheduleReason(""); refresh(); }, onError: error => toast.error(error.message) });
  const saveDebrief = trpc.media.saveDebrief.useMutation({ onSuccess: () => { toast.success("Debriefing salvo."); refresh(); }, onError: error => toast.error(error.message) });
  const updateTraditional = trpc.media.updateTraditionalVeiculation.useMutation({ onSuccess: () => { toast.success("Veiculação mídia volante atualizada."); setEditOpen(false); refresh(); }, onError: error => toast.error(error.message) });

  if (detail.isLoading) return <div className="grid h-56 place-items-center rounded-2xl border border-border bg-card text-sm text-muted-foreground">Carregando veiculação mídia volante...</div>;
  if (!campaign || !point) return <div className="rounded-2xl border border-border bg-card p-8 text-sm text-muted-foreground">A veiculação mídia volante não foi encontrada ou não está disponível para seu perfil.</div>;

  const currentStatus = campaign.status as CampaignStatus;
  const submitStatus = () => { if (["inactive", "cancelled"].includes(pendingStatus) && !statusReason.trim()) { toast.error("Informe o motivo para este status."); return; } if (["inactive", "cancelled"].includes(pendingStatus) && !statusEvidenceIds.length) { toast.error("Anexe uma evidência para este status."); return; } updateStatus.mutate({ campaignId, status: pendingStatus, reason: statusReason.trim() || undefined, evidenceDocumentIds: statusEvidenceIds }); };
  const submitReschedule = () => { if (!rescheduleDates.startsOn || !rescheduleDates.endsOn || !rescheduleReason.trim()) { toast.error("Informe as novas datas e o motivo do reagendamento."); return; } renew.mutate({ sourceCampaignId: campaignId, name: campaign.name, startsOn: rescheduleDates.startsOn, endsOn: rescheduleDates.endsOn, partnershipType: campaign.partnershipType as PartnershipType, estimatedCost: Number(campaign.estimatedCost ?? 0), notes: campaign.notes ?? undefined, campaignDetails: campaign.campaignDetails ?? undefined, rescheduleReason: rescheduleReason.trim(), evidenceDocumentIds: [] }); };
  const saveDebriefForm = () => { if (!debrief.rating || !debrief.resultSummary.trim()) { toast.error("Informe a nota e a história/resultado da veiculação."); return; } saveDebrief.mutate({ campaignId, rating: Number(debrief.rating), resultAchieved: debrief.resultAchieved, feedback: debrief.resultSummary.trim(), debriefHistory: debrief.resultSummary.trim(), debriefResult: debrief.notes.trim() || undefined, debriefEvaluation: debrief.positives.trim() || undefined, debriefLearnings: debrief.negatives.trim() || undefined }); };
  const openEdit = () => { setEditForm({ name: campaign?.name ?? "", startsOn: campaign?.startsOn?.slice(0, 10) ?? "", endsOn: campaign?.endsOn?.slice(0, 10) ?? "", serviceTypeId: campaign?.serviceTypeId ? String(campaign.serviceTypeId) : "", tradeCampaignId: campaign?.tradeCampaignId ? String(campaign.tradeCampaignId) : "", responsibleUserId: campaign?.responsibleUserId ? String(campaign.responsibleUserId) : "", campaignDetails: campaign?.campaignDetails ?? "" }); setEditOpen(true); };
  const submitEdit = (event: React.FormEvent) => { event.preventDefault(); if (!editForm.name.trim() || !editForm.startsOn || !editForm.endsOn) { toast.error("Informe nome e vigência da veiculação."); return; } if (editForm.endsOn < editForm.startsOn) { toast.error("A data final deve ser posterior à data inicial."); return; } updateTraditional.mutate({ campaignId, serviceTypeId: editForm.serviceTypeId ? Number(editForm.serviceTypeId) : null, responsibleUserId: editForm.responsibleUserId ? Number(editForm.responsibleUserId) : null, tradeCampaignId: editForm.tradeCampaignId ? Number(editForm.tradeCampaignId) : null, name: editForm.name.trim(), startsOn: editForm.startsOn, endsOn: editForm.endsOn, campaignDetails: editForm.campaignDetails.trim() || undefined }); };

  return <main className="mx-auto max-w-[1480px] space-y-5">
    <Button type="button" variant="outline" onClick={() => setLocation(`/midias/volante/${point.id}`)} className="border-border"><ArrowLeft className="mr-1.5 h-4 w-4" />Voltar para o programa</Button>
    <header className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-primary">Veiculação de mídia volante</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="font-display text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">{campaign.name}</h1><Badge className="border-0 bg-primary/10 text-primary">{statusLabels[currentStatus] ?? campaign.status}</Badge></div><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Veiculação de rádio ou TV com spot, cidades que recebem o sinal, programação, evidências e debriefing próprios.</p></div>{canWrite && <div className="flex w-full max-w-[480px] flex-wrap items-center justify-end gap-2 xl:shrink-0">{can("tasks.create") ? <ContextTaskDialog entityType="media_campaign" entityId={campaign.id} entityName={campaign.name} cityId={point.cityId} defaultDescription={`Acompanhar a veiculação ${campaign.name} no programa ${point.name}.`} /> : null}<Button type="button" variant="outline" onClick={openEdit} className="border-border"><Pencil className="mr-1.5 h-4 w-4" />Editar</Button><Button type="button" variant="outline" onClick={() => setRescheduleOpen(true)} className="border-primary/30 text-primary"><CalendarClock className="mr-1.5 h-4 w-4" />Reagendar</Button><OperationalStatusDropdown id="volante-campaign-status" value={currentStatus} options={statusOptions} onChange={next => { setPendingStatus(next); setStatusDialog(true); }} disabled={updateStatus.isPending} /></div>}</div></header>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(260px,0.8fr)_minmax(0,1.45fr)]">
      <aside className="min-w-0 space-y-5">
        <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><FileAudio className="h-4 w-4 text-primary" /><div><h2 className="font-display text-lg font-semibold text-foreground">Spot da veiculação</h2><p className="text-xs text-muted-foreground">Adicione ou substitua o áudio da veiculação nesta ficha.</p></div></div><div className="mt-4 min-w-0 overflow-hidden rounded-xl bg-secondary/60"><EvidenceUpload entityType="media_campaign" entityId={campaignId} canWrite={canWrite} documentKind="spot" title="Adicionar spot" variant="side" /></div></article>
        <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Signal className="h-4 w-4 text-primary" /><h2 className="font-display text-lg font-semibold text-foreground">Cidades e programação</h2></div><p className="mt-3 text-sm text-muted-foreground">{campaign.cityDistributions?.length ? `${campaign.cityDistributions.length} cidade(s) recebem o sinal.` : "Nenhuma cidade adicional de sinal informada."}</p><div className="mt-3 flex flex-wrap gap-2">{(campaign.cityDistributions ?? []).map(city => <Badge key={city.cityId} variant="outline" className="border-border">{city.cityName}</Badge>)}</div><div className="mt-5 space-y-2">{(campaign.schedules ?? []).length ? campaign.schedules.map(schedule => <div key={schedule.id} className="rounded-lg border border-border bg-background p-3"><p className="text-sm font-semibold text-foreground">{schedule.programName}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5" />{schedule.specificDate ? formatDate(schedule.specificDate) : ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"][schedule.weekday ?? 0]} · {schedule.startsAt}–{schedule.endsAt}</p></div>) : <p className="text-sm text-muted-foreground">Nenhum horário cadastrado.</p>}</div></article>
        <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Signal className="h-4 w-4 text-primary" /><div><h2 className="font-display text-lg font-semibold text-foreground">Evidências da veiculação</h2><p className="text-xs text-muted-foreground">Gravações, comprovantes e arquivos da execução.</p></div></div><div className="mt-4 min-w-0 overflow-hidden rounded-xl bg-secondary/60"><EvidenceUpload entityType="media_campaign" entityId={campaignId} canWrite={canWrite} documentKind="evidence" title="Adicionar evidência" variant="gallery" /></div></article>
        <OperationalHistory entries={campaign.history ?? []} title="Histórico da veiculação mídia volante" labelFor={entry => { const action = entry.auditAction ?? entry.action ?? ""; return action.startsWith("status_") ? `Status alterado para ${statusLabels[action.replace("status_", "") as CampaignStatus] ?? action}` : action === "reschedule" ? "Veiculação reagendada" : action === "save_debrief" ? "Debriefing atualizado" : action === "update" ? "Veiculação atualizada" : action || "Atualização operacional"; }} evidenceFor={(_entry, payload) => resolveHistoryEvidence(payload, historyDocuments.map(document => ({ id: document.id, url: document.url, originalName: document.originalName })))} />
      </aside>
      <section className="min-w-0 space-y-5">
        <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Volume2 className="h-4 w-4 text-primary" /><h2 className="font-display text-lg font-semibold text-foreground">Dados da veiculação mídia volante</h2></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Programa</dt><dd className="mt-1 font-medium text-foreground">{point.name}</dd></div><div><dt className="text-xs text-muted-foreground">Tipo de mídia</dt><dd className="mt-1 font-medium text-foreground">{point.mediaTypeName}</dd></div><div><dt className="text-xs text-muted-foreground">Vigência</dt><dd className="mt-1 font-medium text-foreground">{formatDate(campaign.startsOn)} — {formatDate(campaign.endsOn)}</dd></div><div><dt className="text-xs text-muted-foreground">Modalidade</dt><dd className="mt-1 font-medium text-foreground">{partnershipLabels[campaign.partnershipType as PartnershipType] ?? campaign.partnershipType}</dd></div><div><dt className="text-xs text-muted-foreground">Serviço</dt><dd className="mt-1 font-medium text-foreground">{campaign.serviceTypeName ?? "Não informado"}</dd></div><div><dt className="text-xs text-muted-foreground">Responsável</dt><dd className="mt-1 font-medium text-foreground">{campaign.responsibleUserName ?? "Não informado"}</dd></div></dl>{campaign.campaignDetails ? <div className="mt-5 rounded-xl bg-secondary/60 p-3 text-sm leading-6 text-foreground"><p className="text-xs font-semibold text-muted-foreground">Detalhes da veiculação</p><p className="mt-1 whitespace-pre-wrap">{campaign.campaignDetails}</p></div> : null}</article>
        <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-primary" /><h2 className="font-display text-lg font-semibold text-foreground">Resumo operacional</h2></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div className="rounded-xl bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">Criada em</p><p className="mt-1 font-medium text-foreground">{formatDateTime(campaign.createdAt)}</p></div><div className="rounded-xl bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">Última atualização</p><p className="mt-1 font-medium text-foreground">{formatDateTime(campaign.updatedAt)}</p></div><div className="rounded-xl bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">Alcance</p><p className="mt-1 flex items-center gap-1 font-medium text-foreground"><UsersRound className="h-3.5 w-3.5 text-primary" />{point.signalRangeKm ? `${point.signalRangeKm} km` : "Não informado"}</p></div><div className="rounded-xl bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">Local</p><p className="mt-1 flex items-center gap-1 font-medium text-foreground"><MapPin className="h-3.5 w-3.5 text-primary" />{point.cityName}</p></div></div></article>
        <OperationalDebriefing value={debrief} onChange={setDebrief} onSave={saveDebriefForm} pending={saveDebrief.isPending} canWrite={canWrite} title="Debriefing e resultado da veiculação" summaryLabel="História e resultado da propaganda" />
      </section>
    </div>
    <Dialog open={editOpen} onOpenChange={setEditOpen}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Editar veiculação mídia volante</DialogTitle><DialogDescription>Atualize os dados principais sem sair do histórico da veiculação.</DialogDescription></DialogHeader><form onSubmit={submitEdit} className="grid gap-4 pt-2 md:grid-cols-2"><label className="space-y-1.5 md:col-span-2"><Label htmlFor="traditional-edit-name">Nome da veiculação</Label><Input id="traditional-edit-name" required value={editForm.name} onChange={event => setEditForm({ ...editForm, name: event.target.value })} /></label><div><SearchableMultiSelect id="traditional-edit-service" label="Tipo de serviço" options={serviceOptions} values={editForm.serviceTypeId ? [Number(editForm.serviceTypeId)] : []} onChange={values => setEditForm({ ...editForm, serviceTypeId: values[0] ? String(values[0]) : "" })} maxSelections={1} placeholder="Selecionar serviço" emptyMessage="Nenhum serviço disponível" /></div><div><SearchableMultiSelect id="traditional-edit-campaign" label="Campanha vinculada" options={campaignOptions} values={editForm.tradeCampaignId ? [Number(editForm.tradeCampaignId)] : []} onChange={values => setEditForm({ ...editForm, tradeCampaignId: values[0] ? String(values[0]) : "" })} maxSelections={1} placeholder="Nenhuma campanha" emptyMessage="Nenhuma campanha disponível" /></div><label className="space-y-1.5"><Label>Início</Label><Input required type="date" value={editForm.startsOn} onChange={event => setEditForm({ ...editForm, startsOn: event.target.value })} /></label><label className="space-y-1.5"><Label>Fim</Label><Input required type="date" value={editForm.endsOn} onChange={event => setEditForm({ ...editForm, endsOn: event.target.value })} /></label><div className="md:col-span-2"><SearchableMultiSelect id="traditional-edit-responsible" label="Responsável do trade" options={responsibleOptions} values={editForm.responsibleUserId ? [Number(editForm.responsibleUserId)] : []} onChange={values => setEditForm({ ...editForm, responsibleUserId: values[0] ? String(values[0]) : "" })} maxSelections={1} placeholder="Não definido" emptyMessage="Nenhum responsável disponível" /></div><label className="space-y-1.5 md:col-span-2"><Label>Detalhes da veiculação <span className="font-normal text-muted-foreground">(opcional)</span></Label><Textarea value={editForm.campaignDetails} onChange={event => setEditForm({ ...editForm, campaignDetails: event.target.value })} placeholder="Objetivo, formato, duração do spot ou entregas." /></label><div className="flex justify-end gap-2 md:col-span-2"><Button type="button" variant="outline" onClick={() => setEditOpen(false)}>Cancelar</Button><Button type="submit" disabled={updateTraditional.isPending}>{updateTraditional.isPending ? "Salvando..." : "Salvar alterações"}</Button></div></form></DialogContent></Dialog>
    <Dialog open={rescheduleOpen} onOpenChange={setRescheduleOpen}><DialogContent><DialogHeader><DialogTitle>Reagendar veiculação</DialogTitle><DialogDescription>A veiculação será atualizada no mesmo registro, sem criar uma duplicata.</DialogDescription></DialogHeader><div className="grid gap-4"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5"><Label>Nova data de início</Label><Input type="date" value={rescheduleDates.startsOn} onChange={event => setRescheduleDates({ ...rescheduleDates, startsOn: event.target.value })} /></label><label className="grid gap-1.5"><Label>Nova data de fim</Label><Input type="date" value={rescheduleDates.endsOn} onChange={event => setRescheduleDates({ ...rescheduleDates, endsOn: event.target.value })} /></label></div><label className="grid gap-1.5"><Label>Motivo</Label><Textarea value={rescheduleReason} onChange={event => setRescheduleReason(event.target.value)} placeholder="Explique o motivo do reagendamento." /></label><Button type="button" onClick={submitReschedule} disabled={renew.isPending}>{renew.isPending ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : null}Confirmar reagendamento</Button></div></DialogContent></Dialog>
    <OperationalStatusDialog open={statusDialog} onOpenChange={setStatusDialog} reason={statusReason} onReasonChange={setStatusReason} requiredReason={pendingStatus === "inactive" || pendingStatus === "cancelled"} evidenceCount={statusEvidenceIds.length} evidenceContent={<EvidenceUpload entityType="media_campaign" entityId={campaignId} canWrite={canWrite} documentKind="history_evidence" title="Evidências do motivo" onUploadComplete={document => setStatusEvidenceIds(current => current.includes(document.id) ? current : [...current, document.id])} />} pending={updateStatus.isPending} onSubmit={submitStatus} />
  </main>;
}
