import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Building2, MapPinned, Plus, Settings2, Store, Tags, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import SupplierCoverageManager from "@/components/SupplierCoverageManager";

export function normalizeRegistryValue(value: string) {
  return value.trim().toLocaleLowerCase("pt-BR");
}

export function hasDuplicateRegistryValue(values: Array<string | null | undefined>, candidate: string) {
  const normalizedCandidate = normalizeRegistryValue(candidate);
  return normalizedCandidate.length > 0 && values.some(value => normalizeRegistryValue(value ?? "") === normalizedCandidate);
}

export function digitsOnly(value: string) {
  return value.replace(/\D/g, "");
}

export default function SettingsWorkspace() {
  const utils = trpc.useUtils();
  const data = trpc.settings.overview.useQuery();
  const [providerName, setProviderName] = useState("");
  const [regional, setRegional] = useState({ name: "", code: "", providerId: "" });
  const [city, setCity] = useState({ name: "", state: "", regionalId: "" });
  const [supplier, setSupplier] = useState({ displayName: "", email: "", phone: "", document: "", providerId: "" });
  const [store, setStore] = useState({ name: "", code: "", cityId: "" });
  const [partner, setPartner] = useState({ name: "", email: "" });
  const [catalogType, setCatalogType] = useState({ kind: "service" as "service" | "media" | "action" | "event", name: "" });
  const refresh = () => utils.settings.overview.invalidate();
  const addProvider = trpc.settings.createProvider.useMutation({ onSuccess: () => { toast.success("Prestador cadastrado."); setProviderName(""); refresh(); }, onError: error => toast.error(error.message) });
  const addRegional = trpc.settings.createRegional.useMutation({ onSuccess: () => { toast.success("Regional cadastrada."); setRegional({ name: "", code: "", providerId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addCity = trpc.settings.createCity.useMutation({ onSuccess: () => { toast.success("Cidade cadastrada."); setCity({ name: "", state: "", regionalId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addSupplier = trpc.settings.createSupplier.useMutation({ onSuccess: () => { toast.success("Fornecedor cadastrado."); setSupplier({ displayName: "", email: "", phone: "", document: "", providerId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addStore = trpc.settings.createStore.useMutation({ onSuccess: () => { toast.success("Loja cadastrada."); setStore({ name: "", code: "", cityId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addPartner = trpc.settings.createPartner.useMutation({ onSuccess: () => { toast.success("Parceiro cadastrado."); setPartner({ name: "", email: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addType = trpc.settings.createType.useMutation({ onSuccess: () => { toast.success("Tipologia cadastrada."); setCatalogType({ ...catalogType, name: "" }); refresh(); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-[1480px]"><div className="flex gap-4 border-b border-border pb-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-primary text-white shadow-sm"><Settings2 className="h-5 w-5" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-foreground">Base cadastral</p><h1 className="mt-1 font-display text-3xl font-semibold tracking-tight text-foreground">Configurações</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-foreground">Estruture a hierarquia territorial e a rede de parceiros para iniciar sua operação.</p></div></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><form onSubmit={(event: FormEvent) => { event.preventDefault(); if (hasDuplicateRegistryValue(data.data?.providers.map(row => row.name) ?? [], providerName)) return toast.error("Já existe um prestador com este nome."); addProvider.mutate({ name: providerName.trim() }); }} className="rounded-2xl border border-border bg-white p-5"><div className="flex items-center gap-3"><Building2 className="h-4 w-4 text-foreground" /><h2 className="font-display text-lg font-semibold text-foreground">Prestadores</h2></div><p className="mt-1 text-xs text-foreground">Entidade responsável por regionais e fornecedores.</p><div className="mt-5 flex gap-2"><Input required minLength={2} placeholder="Nome do prestador" value={providerName} onChange={event => setProviderName(event.target.value)} /><Button type="submit" aria-label="Adicionar prestador" disabled={addProvider.isPending} className="bg-primary hover:bg-primary/90"><Plus className="h-4 w-4" /></Button></div><p className="mt-4 text-xs text-foreground">{data.data?.providers.length ?? 0} cadastrados</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); const sameRegional = data.data?.regionals.some(row => normalizeRegistryValue(row.name) === normalizeRegistryValue(regional.name) || normalizeRegistryValue(row.code) === normalizeRegistryValue(regional.code)); if (sameRegional) return toast.error("Já existe uma regional com este nome ou código."); addRegional.mutate({ name: regional.name.trim(), code: regional.code.trim().toUpperCase(), providerId: regional.providerId ? Number(regional.providerId) : null }); }} className="rounded-2xl border border-border bg-white p-5"><div className="flex items-center gap-3"><MapPinned className="h-4 w-4 text-foreground" /><h2 className="font-display text-lg font-semibold text-foreground">Regionais</h2></div><p className="mt-1 text-xs text-foreground">Estrutura territorial de controle e responsabilidade.</p><div className="mt-5 grid gap-2 sm:grid-cols-3"><Input required minLength={2} placeholder="Nome" value={regional.name} onChange={event => setRegional({ ...regional, name: event.target.value })} /><Input required minLength={2} placeholder="Código" value={regional.code} onChange={event => setRegional({ ...regional, code: event.target.value.toUpperCase() })} /><select aria-label="Prestador da regional" value={regional.providerId} onChange={event => setRegional({ ...regional, providerId: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Sem prestador</option>{data.data?.providers.map(provider => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></div><Button type="submit" disabled={addRegional.isPending} className="mt-3 bg-primary hover:bg-primary/90">Adicionar regional</Button><p className="mt-4 text-xs text-foreground">{data.data?.regionals.length ?? 0} cadastradas</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); if (city.state.trim().length !== 2) return toast.error("Informe uma UF com duas letras."); const sameCity = data.data?.cities.some(row => row.regionalId === Number(city.regionalId) && normalizeRegistryValue(row.name) === normalizeRegistryValue(city.name) && normalizeRegistryValue(row.state) === normalizeRegistryValue(city.state)); if (sameCity) return toast.error("Esta cidade já está cadastrada na regional selecionada."); addCity.mutate({ name: city.name.trim(), state: city.state.trim().toUpperCase(), regionalId: Number(city.regionalId) }); }} className="rounded-2xl border border-border bg-white p-5"><div className="flex items-center gap-3"><MapPinned className="h-4 w-4 text-foreground" /><h2 className="font-display text-lg font-semibold text-foreground">Cidades</h2></div><p className="mt-1 text-xs text-foreground">Cidades vinculadas à regional responsável.</p><div className="mt-5 grid gap-2 sm:grid-cols-3"><Input required minLength={2} placeholder="Cidade" value={city.name} onChange={event => setCity({ ...city, name: event.target.value })} /><Input required maxLength={2} minLength={2} pattern="[A-Z]{2}" placeholder="UF" value={city.state} onChange={event => setCity({ ...city, state: event.target.value.toUpperCase() })} /><select aria-label="Regional da cidade" required value={city.regionalId} onChange={event => setCity({ ...city, regionalId: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Regional</option>{data.data?.regionals.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><Button type="submit" disabled={addCity.isPending} className="mt-3 bg-primary hover:bg-primary/90">Adicionar cidade</Button><p className="mt-4 text-xs text-foreground">{data.data?.cities.length ?? 0} cadastradas</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); const cnpj = digitsOnly(supplier.document); if (cnpj.length !== 14) return toast.error("Informe um CNPJ com 14 dígitos."); if (hasDuplicateRegistryValue(data.data?.suppliers.map(row => row.displayName) ?? [], supplier.displayName)) return toast.error("Já existe um fornecedor com este nome de exibição."); if (hasDuplicateRegistryValue(data.data?.suppliers.map(row => digitsOnly(row.document ?? "")) ?? [], cnpj)) return toast.error("Já existe um fornecedor cadastrado com este CNPJ."); addSupplier.mutate({ displayName: supplier.displayName.trim(), email: supplier.email.trim(), phone: supplier.phone.trim(), document: cnpj, providerId: supplier.providerId ? Number(supplier.providerId) : null }); }} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-3"><UsersRound className="h-4 w-4 text-foreground" /><h2 className="font-display text-lg font-semibold text-foreground">Fornecedores</h2></div><p className="mt-1 text-xs text-muted-foreground">Nome, e-mail, telefone e CNPJ obrigatórios para mídia, ações, eventos e financeiro.</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><Input required minLength={2} placeholder="Nome de exibição" value={supplier.displayName} onChange={event => setSupplier({ ...supplier, displayName: event.target.value })} /><Input required placeholder="CNPJ" inputMode="numeric" minLength={14} maxLength={18} value={supplier.document} onChange={event => setSupplier({ ...supplier, document: event.target.value })} /><Input required placeholder="E-mail" type="email" value={supplier.email} onChange={event => setSupplier({ ...supplier, email: event.target.value })} /><Input required placeholder="Telefone" type="tel" minLength={8} value={supplier.phone} onChange={event => setSupplier({ ...supplier, phone: event.target.value })} /><select aria-label="Prestador do fornecedor" value={supplier.providerId} onChange={event => setSupplier({ ...supplier, providerId: event.target.value })} className="h-9 rounded-md border border-input bg-background px-3 text-sm sm:col-span-2"><option value="">Sem prestador</option>{data.data?.providers.map(provider => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></div><Button type="submit" disabled={addSupplier.isPending} className="mt-3 bg-primary hover:bg-primary/90">Adicionar fornecedor</Button><p className="mt-4 text-xs text-muted-foreground">{data.data?.suppliers.length ?? 0} cadastrados</p></form></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-3"><form onSubmit={(event: FormEvent) => { event.preventDefault(); const sameStore = data.data?.stores.some(row => normalizeRegistryValue(row.code) === normalizeRegistryValue(store.code) || (row.cityId === Number(store.cityId) && normalizeRegistryValue(row.name) === normalizeRegistryValue(store.name))); if (sameStore) return toast.error("Já existe uma loja com este código ou nome na cidade selecionada."); addStore.mutate({ name: store.name.trim(), code: store.code.trim().toUpperCase(), cityId: Number(store.cityId) }); }} className="rounded-2xl border border-border bg-white p-5"><div className="flex items-center gap-3"><Store className="h-4 w-4 text-foreground" /><h2 className="font-display text-lg font-semibold text-foreground">Lojas</h2></div><p className="mt-1 text-xs text-foreground">Pontos de venda vinculados às cidades da operação.</p><div className="mt-5 grid gap-2"><Input required minLength={2} placeholder="Nome da loja" value={store.name} onChange={event => setStore({ ...store, name: event.target.value })} /><div className="grid grid-cols-2 gap-2"><Input required minLength={2} placeholder="Código" value={store.code} onChange={event => setStore({ ...store, code: event.target.value.toUpperCase() })} /><select aria-label="Cidade da loja" required value={store.cityId} onChange={event => setStore({ ...store, cityId: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Cidade</option>{data.data?.cities.map(row => <option key={row.id} value={row.id}>{row.name} - {row.state}</option>)}</select></div></div><Button type="submit" disabled={addStore.isPending} className="mt-3 bg-primary hover:bg-primary/90">Adicionar loja</Button><p className="mt-4 text-xs text-foreground">{data.data?.stores.length ?? 0} cadastradas</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); if (hasDuplicateRegistryValue(data.data?.partners.map(row => row.name) ?? [], partner.name)) return toast.error("Já existe um parceiro com este nome."); addPartner.mutate({ name: partner.name.trim(), email: partner.email.trim() || undefined }); }} className="rounded-2xl border border-border bg-white p-5"><div className="flex items-center gap-3"><UsersRound className="h-4 w-4 text-foreground" /><h2 className="font-display text-lg font-semibold text-foreground">Parceiros</h2></div><p className="mt-1 text-xs text-foreground">Parceiros institucionais e interlocutores da operação.</p><div className="mt-5 grid gap-2"><Input required minLength={2} placeholder="Nome do parceiro" value={partner.name} onChange={event => setPartner({ ...partner, name: event.target.value })} /><Input type="email" placeholder="E-mail" value={partner.email} onChange={event => setPartner({ ...partner, email: event.target.value })} /></div><Button type="submit" disabled={addPartner.isPending} className="mt-3 bg-primary hover:bg-primary/90">Adicionar parceiro</Button><p className="mt-4 text-xs text-foreground">{data.data?.partners.length ?? 0} cadastrados</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); const currentTypes = catalogType.kind === "service" ? data.data?.serviceTypes : catalogType.kind === "media" ? data.data?.mediaTypes : catalogType.kind === "action" ? data.data?.actionTypes : data.data?.eventTypes; if (hasDuplicateRegistryValue(currentTypes?.map(row => row.name) ?? [], catalogType.name)) return toast.error("Esta tipologia já está cadastrada nesta categoria."); addType.mutate({ ...catalogType, name: catalogType.name.trim() }); }} className="rounded-2xl border border-border bg-white p-5"><div className="flex items-center gap-3"><Tags className="h-4 w-4 text-foreground" /><h2 className="font-display text-lg font-semibold text-foreground">Tipos operacionais</h2></div><p className="mt-1 text-xs text-foreground">Classificações de serviços, mídias, ações e eventos.</p><div className="mt-5 grid gap-2"><select aria-label="Categoria da tipologia" value={catalogType.kind} onChange={event => setCatalogType({ ...catalogType, kind: event.target.value as typeof catalogType.kind })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="service">Tipo de serviço</option><option value="media">Tipo de mídia</option><option value="action">Tipo de ação</option><option value="event">Tipo de evento</option></select><Input required minLength={2} placeholder="Nome da tipologia" value={catalogType.name} onChange={event => setCatalogType({ ...catalogType, name: event.target.value })} /></div><Button type="submit" disabled={addType.isPending} className="mt-3 bg-primary hover:bg-primary/90">Adicionar tipo</Button><p className="mt-4 text-xs text-foreground">{(data.data?.serviceTypes.length ?? 0) + (data.data?.mediaTypes.length ?? 0) + (data.data?.actionTypes.length ?? 0) + (data.data?.eventTypes.length ?? 0)} tipologias cadastradas</p></form></div><SupplierCoverageManager /></div>;
}
