import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Building2, MapPinned, Plus, Settings2, Store, Tags, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import SupplierCoverageManager from "@/components/SupplierCoverageManager";

export default function SettingsWorkspace() {
  const utils = trpc.useUtils();
  const data = trpc.settings.overview.useQuery();
  const [providerName, setProviderName] = useState("");
  const [regional, setRegional] = useState({ name: "", code: "", providerId: "" });
  const [city, setCity] = useState({ name: "", state: "", regionalId: "" });
  const [supplier, setSupplier] = useState({ displayName: "", email: "", providerId: "" });
  const [store, setStore] = useState({ name: "", code: "", cityId: "" });
  const [partner, setPartner] = useState({ name: "", email: "" });
  const [catalogType, setCatalogType] = useState({ kind: "service" as "service" | "media" | "action" | "event", name: "" });
  const refresh = () => utils.settings.overview.invalidate();
  const addProvider = trpc.settings.createProvider.useMutation({ onSuccess: () => { toast.success("Prestador cadastrado."); setProviderName(""); refresh(); }, onError: error => toast.error(error.message) });
  const addRegional = trpc.settings.createRegional.useMutation({ onSuccess: () => { toast.success("Regional cadastrada."); setRegional({ name: "", code: "", providerId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addCity = trpc.settings.createCity.useMutation({ onSuccess: () => { toast.success("Cidade cadastrada."); setCity({ name: "", state: "", regionalId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addSupplier = trpc.settings.createSupplier.useMutation({ onSuccess: () => { toast.success("Fornecedor cadastrado."); setSupplier({ displayName: "", email: "", providerId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addStore = trpc.settings.createStore.useMutation({ onSuccess: () => { toast.success("Loja cadastrada."); setStore({ name: "", code: "", cityId: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addPartner = trpc.settings.createPartner.useMutation({ onSuccess: () => { toast.success("Parceiro cadastrado."); setPartner({ name: "", email: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const addType = trpc.settings.createType.useMutation({ onSuccess: () => { toast.success("Tipologia cadastrada."); setCatalogType({ ...catalogType, name: "" }); refresh(); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-[1480px]"><div className="flex gap-4 border-b border-[#dce3db] pb-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#45604f] text-white shadow-sm"><Settings2 className="h-5 w-5" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#758780]">Base cadastral</p><h1 className="mt-1 font-display text-3xl font-semibold tracking-tight text-[#203735]">Configurações</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6f817b]">Estruture a hierarquia territorial e a rede de parceiros para iniciar sua operação.</p></div></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><form onSubmit={(event: FormEvent) => { event.preventDefault(); addProvider.mutate({ name: providerName }); }} className="rounded-2xl border border-[#e0e5dd] bg-white p-5"><div className="flex items-center gap-3"><Building2 className="h-4 w-4 text-[#476553]" /><h2 className="font-display text-lg font-semibold text-[#2f4540]">Prestadores</h2></div><p className="mt-1 text-xs text-[#778781]">Entidade responsável por regionais e fornecedores.</p><div className="mt-5 flex gap-2"><Input required placeholder="Nome do prestador" value={providerName} onChange={event => setProviderName(event.target.value)} /><Button type="submit" aria-label="Adicionar prestador" disabled={addProvider.isPending} className="bg-[#45604f] hover:bg-[#354d40]"><Plus className="h-4 w-4" /></Button></div><p className="mt-4 text-xs text-[#6d7d76]">{data.data?.providers.length ?? 0} cadastrados</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); addRegional.mutate({ name: regional.name, code: regional.code, providerId: regional.providerId ? Number(regional.providerId) : null }); }} className="rounded-2xl border border-[#e0e5dd] bg-white p-5"><div className="flex items-center gap-3"><MapPinned className="h-4 w-4 text-[#476553]" /><h2 className="font-display text-lg font-semibold text-[#2f4540]">Regionais</h2></div><p className="mt-1 text-xs text-[#778781]">Estrutura territorial de controle e responsabilidade.</p><div className="mt-5 grid gap-2 sm:grid-cols-3"><Input required placeholder="Nome" value={regional.name} onChange={event => setRegional({ ...regional, name: event.target.value })} /><Input required placeholder="Código" value={regional.code} onChange={event => setRegional({ ...regional, code: event.target.value })} /><select aria-label="Prestador da regional" value={regional.providerId} onChange={event => setRegional({ ...regional, providerId: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Sem prestador</option>{data.data?.providers.map(provider => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></div><Button type="submit" disabled={addRegional.isPending} className="mt-3 bg-[#45604f] hover:bg-[#354d40]">Adicionar regional</Button><p className="mt-4 text-xs text-[#6d7d76]">{data.data?.regionals.length ?? 0} cadastradas</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); addCity.mutate({ name: city.name, state: city.state, regionalId: Number(city.regionalId) }); }} className="rounded-2xl border border-[#e0e5dd] bg-white p-5"><div className="flex items-center gap-3"><MapPinned className="h-4 w-4 text-[#476553]" /><h2 className="font-display text-lg font-semibold text-[#2f4540]">Cidades</h2></div><p className="mt-1 text-xs text-[#778781]">Cidades vinculadas à regional responsável.</p><div className="mt-5 grid gap-2 sm:grid-cols-3"><Input required placeholder="Cidade" value={city.name} onChange={event => setCity({ ...city, name: event.target.value })} /><Input required maxLength={2} placeholder="UF" value={city.state} onChange={event => setCity({ ...city, state: event.target.value.toUpperCase() })} /><select aria-label="Regional da cidade" required value={city.regionalId} onChange={event => setCity({ ...city, regionalId: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Regional</option>{data.data?.regionals.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><Button type="submit" disabled={addCity.isPending} className="mt-3 bg-[#45604f] hover:bg-[#354d40]">Adicionar cidade</Button><p className="mt-4 text-xs text-[#6d7d76]">{data.data?.cities.length ?? 0} cadastradas</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); addSupplier.mutate({ displayName: supplier.displayName, email: supplier.email || undefined, providerId: supplier.providerId ? Number(supplier.providerId) : null }); }} className="rounded-2xl border border-[#e0e5dd] bg-white p-5"><div className="flex items-center gap-3"><UsersRound className="h-4 w-4 text-[#476553]" /><h2 className="font-display text-lg font-semibold text-[#2f4540]">Fornecedores</h2></div><p className="mt-1 text-xs text-[#778781]">Parceiros usados em mídias, ações, eventos e financeiro.</p><div className="mt-5 grid gap-2 sm:grid-cols-3"><Input required placeholder="Nome de exibição" value={supplier.displayName} onChange={event => setSupplier({ ...supplier, displayName: event.target.value })} /><Input placeholder="E-mail" type="email" value={supplier.email} onChange={event => setSupplier({ ...supplier, email: event.target.value })} /><select aria-label="Prestador do fornecedor" value={supplier.providerId} onChange={event => setSupplier({ ...supplier, providerId: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Sem prestador</option>{data.data?.providers.map(provider => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></div><Button type="submit" disabled={addSupplier.isPending} className="mt-3 bg-[#45604f] hover:bg-[#354d40]">Adicionar fornecedor</Button><p className="mt-4 text-xs text-[#6d7d76]">{data.data?.suppliers.length ?? 0} cadastrados</p></form></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-3"><form onSubmit={(event: FormEvent) => { event.preventDefault(); addStore.mutate({ name: store.name, code: store.code, cityId: Number(store.cityId) }); }} className="rounded-2xl border border-[#e0e5dd] bg-white p-5"><div className="flex items-center gap-3"><Store className="h-4 w-4 text-[#476553]" /><h2 className="font-display text-lg font-semibold text-[#2f4540]">Lojas</h2></div><p className="mt-1 text-xs text-[#778781]">Pontos de venda vinculados às cidades da operação.</p><div className="mt-5 grid gap-2"><Input required placeholder="Nome da loja" value={store.name} onChange={event => setStore({ ...store, name: event.target.value })} /><div className="grid grid-cols-2 gap-2"><Input required placeholder="Código" value={store.code} onChange={event => setStore({ ...store, code: event.target.value })} /><select aria-label="Cidade da loja" required value={store.cityId} onChange={event => setStore({ ...store, cityId: event.target.value })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="">Cidade</option>{data.data?.cities.map(row => <option key={row.id} value={row.id}>{row.name} - {row.state}</option>)}</select></div></div><Button type="submit" disabled={addStore.isPending} className="mt-3 bg-[#45604f] hover:bg-[#354d40]">Adicionar loja</Button><p className="mt-4 text-xs text-[#6d7d76]">{data.data?.stores.length ?? 0} cadastradas</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); addPartner.mutate({ name: partner.name, email: partner.email || undefined }); }} className="rounded-2xl border border-[#e0e5dd] bg-white p-5"><div className="flex items-center gap-3"><UsersRound className="h-4 w-4 text-[#476553]" /><h2 className="font-display text-lg font-semibold text-[#2f4540]">Parceiros</h2></div><p className="mt-1 text-xs text-[#778781]">Parceiros institucionais e interlocutores da operação.</p><div className="mt-5 grid gap-2"><Input required placeholder="Nome do parceiro" value={partner.name} onChange={event => setPartner({ ...partner, name: event.target.value })} /><Input type="email" placeholder="E-mail" value={partner.email} onChange={event => setPartner({ ...partner, email: event.target.value })} /></div><Button type="submit" disabled={addPartner.isPending} className="mt-3 bg-[#45604f] hover:bg-[#354d40]">Adicionar parceiro</Button><p className="mt-4 text-xs text-[#6d7d76]">{data.data?.partners.length ?? 0} cadastrados</p></form>
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); addType.mutate(catalogType); }} className="rounded-2xl border border-[#e0e5dd] bg-white p-5"><div className="flex items-center gap-3"><Tags className="h-4 w-4 text-[#476553]" /><h2 className="font-display text-lg font-semibold text-[#2f4540]">Tipos operacionais</h2></div><p className="mt-1 text-xs text-[#778781]">Classificações de serviços, mídias, ações e eventos.</p><div className="mt-5 grid gap-2"><select aria-label="Categoria da tipologia" value={catalogType.kind} onChange={event => setCatalogType({ ...catalogType, kind: event.target.value as typeof catalogType.kind })} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"><option value="service">Tipo de serviço</option><option value="media">Tipo de mídia</option><option value="action">Tipo de ação</option><option value="event">Tipo de evento</option></select><Input required placeholder="Nome da tipologia" value={catalogType.name} onChange={event => setCatalogType({ ...catalogType, name: event.target.value })} /></div><Button type="submit" disabled={addType.isPending} className="mt-3 bg-[#45604f] hover:bg-[#354d40]">Adicionar tipo</Button><p className="mt-4 text-xs text-[#6d7d76]">{(data.data?.serviceTypes.length ?? 0) + (data.data?.mediaTypes.length ?? 0) + (data.data?.actionTypes.length ?? 0) + (data.data?.eventTypes.length ?? 0)} tipologias cadastradas</p></form></div><SupplierCoverageManager /></div>;
}
