import EvidenceUpload from "@/components/EvidenceUpload";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useEffectivePermissions } from "@/hooks/useEffectivePermissions";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Building2, CalendarClock, CheckCircle2, CircleDot, Clock3, ExternalLink, FileImage, History, MapPin, PencilLine, RefreshCw, XCircle } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

const statusLabels: Record<string, string> = { scheduled: "Planejada", active: "Em veiculação", completed: "Encerrada", cancelled: "Cancelada" };
const statusStyle: Record<string, string> = { scheduled: "bg-amber-500/10 text-amber-700", active: "bg-primary/10 text-primary", completed: "bg-emerald-500/10 text-emerald-700", cancelled: "bg-red-500/10 text-red-700" };
const emptyDebrief = { rating: "", resultAchieved: true, feedback: "" };
const emptyRenewal = { startsOn: "", endsOn: "", name: "", estimatedCost: "", reason: "" };

export default function UrbanVeiculationPage() {
  const [, params] = useRoute("/midias/veiculacao/:campaignId");
  const campaignId = Number(params?.campaignId ?? 0);
  const [, setLocation] = useLocation();
  const { can } = useEffectivePermissions();
  const canWrite = can("media.write");
  const utils = trpc.useUtils();
  const detail = trpc.media.campaignDetails.useQuery({ campaignId }, { enabled: Boolean(campaignId) });
  const [debrief, setDebrief] = useState(emptyDebrief);
  const [renewal, setRenewal] = useState(emptyRenewal);
  const [renewalOpen, setRenewalOpen] = useState(false);
  const [reasonOpen, setReasonOpen] = useState(false);
  const [reason, setReason] = useState("");
  const campaign = detail.data;
  const refresh = () => { void utils.media.campaignDetails.invalidate({ campaignId }); void utils.media.pointDetails.invalidate(); void utils.media.list.invalidate(); };
  const updateStatus = trpc.media.updateCampaignStatus.useMutation({ onSuccess: () => { toast.success("Status da veiculação atualizado."); setReasonOpen(false); setReason(""); refresh(); }, onError: error => toast.error(error.message) });
  const saveDebrief = trpc.media.saveDebrief.useMutation({ onSuccess: () => { toast.success("Debriefing salvo."); refresh(); }, onError: error => toast.error(error.message) });
  const renew = trpc.media.renewCampaign.useMutation({ onSuccess: result => { toast.success("Veiculação reagendada com histórico preservado."); setRenewalOpen(false); setLocation(`/midias/veiculacao/${result.id}`); }, onError: error => toast.error(error.message) });
  const submitDebrief = (event: FormEvent) => { event.preventDefault(); saveDebrief.mutate({ campaignId, rating: Number(debrief.rating), resultAchieved: debrief.resultAchieved, feedback: debrief.feedback }); };
  const submitRenewal = (event: FormEvent) => { event.preventDefault(); if (!campaign) return; renew.mutate({ sourceCampaignId: campaign.id, name: renewal.name || campaign.name, startsOn: renewal.startsOn, endsOn: renewal.endsOn, partnershipType: campaign.partnershipType as "paid" | "barter" | "mixed", estimatedCost: renewal.estimatedCost ? Number(renewal.estimatedCost) : Number(campaign.estimatedCost), notes: campaign.notes || undefined, campaignDetails: campaign.campaignDetails || undefined, rescheduleReason: renewal.reason }); };
  const startRenewal = () => { if (!campaign) return; setRenewal({ startsOn: "", endsOn: "", name: campaign.name, estimatedCost: String(campaign.estimatedCost), reason: "" }); setRenewalOpen(true); };
  const changeStatus = (nextStatus: "scheduled" | "active" | "completed" | "cancelled") => { if (nextStatus === "cancelled") { setReasonOpen(true); return; } updateStatus.mutate({ campaignId, status: nextStatus }); };

  if (detail.isLoading) return <div className="grid h-56 place-items-center rounded-2xl border border-border bg-card text-sm text-muted-foreground">Carregando veiculação...</div>;
  if (!campaign) return <div className="rounded-2xl border border-border bg-card p-8 text-sm text-muted-foreground">A veiculação não foi encontrada ou não está disponível para seu perfil.</div>;
  const statusActions = [
    { value: "scheduled" as const, label: "Planejada", icon: Clock3 },
    { value: "active" as const, label: "Em veiculação", icon: CircleDot },
    { value: "completed" as const, label: "Encerrada", icon: CheckCircle2 },
    { value: "cancelled" as const, label: "Cancelar", icon: XCircle },
  ];
  return <main className="mx-auto max-w-6xl space-y-5">
    <Button type="button" variant="outline" onClick={() => setLocation(`/midias/${campaign.mediaPointId}`)} className="border-border"><ArrowLeft className="mr-1.5 h-4 w-4" />Voltar para o ponto de mídia</Button>
    <header className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-primary">Veiculação de mídia urbana</p><Badge className={`border-0 text-[10px] ${statusStyle[campaign.status]}`}>{statusLabels[campaign.status]}</Badge></div><h1 className="mt-2 font-display text-3xl font-semibold text-foreground">{campaign.name}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{campaign.objective || "Objetivo não informado"}</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5 rounded-lg bg-secondary px-2.5 py-1.5"><CalendarClock className="h-3.5 w-3.5 text-primary" />{new Date(`${campaign.startsOn}T12:00:00`).toLocaleDateString("pt-BR")} a {new Date(`${campaign.endsOn}T12:00:00`).toLocaleDateString("pt-BR")}</span><span className="inline-flex items-center gap-1.5 rounded-lg bg-secondary px-2.5 py-1.5">{Number(campaign.estimatedCost).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</span></div></div>{canWrite && <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={startRenewal} className="border-primary/30 text-primary"><RefreshCw className="mr-1.5 h-4 w-4" />Reagendar</Button></div>}</div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{statusActions.map(action => { const Icon = action.icon; const selected = campaign.status === action.value; return <button key={action.value} type="button" disabled={!canWrite || updateStatus.isPending} onClick={() => changeStatus(action.value)} className={`rounded-xl border p-3 text-left transition ${selected ? "border-primary bg-primary/5" : "border-border bg-card hover:border-primary/40"}`}><Icon className={`h-4 w-4 ${selected ? "text-primary" : "text-muted-foreground"}`} /><p className={`mt-2 text-sm font-semibold ${selected ? "text-primary" : "text-foreground"}`}>{action.label}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{selected ? "Status atual" : "Atualizar status"}</p></button>})}</section>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="space-y-5"><article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-primary" /><div><p className="font-display text-lg font-semibold text-foreground">Planejamento e mídia</p><p className="text-xs text-muted-foreground">Dados que identificam a veiculação, o ponto e seu vínculo contratual.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info label="Ponto físico" value={campaign.point.name} /><Info label="Fornecedor" value={campaign.point.supplierName} /><Info label="Cidade e regional" value={`${campaign.point.cityName} · ${campaign.point.regionalName}`} /><Info label="Subtipo e variação" value={`${campaign.point.mediaTypeName}${campaign.registration?.variationName ? ` · ${campaign.registration.variationName}` : ""}`} /><Info label="Contrato" value={campaign.registration?.contract?.contractCode || campaign.registration?.contractReference || "Não vinculado"} /><Info label="Campanha vinculada" value={campaign.tradeCampaignName || "Não vinculada"} /></div>{campaign.campaignDetails && <div className="mt-5 rounded-xl bg-secondary p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Detalhes da veiculação</p><p className="mt-2 text-sm leading-6 text-foreground">{campaign.campaignDetails}</p></div>}{campaign.notes && <div className="mt-4 rounded-xl border border-border p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Observações</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-foreground">{campaign.notes}</p></div>}</article>
      <article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><PencilLine className="h-4 w-4 text-primary" /><div><p className="font-display text-lg font-semibold text-foreground">Debriefing</p><p className="text-xs text-muted-foreground">Registre a avaliação e os aprendizados da veiculação.</p></div></div><form onSubmit={submitDebrief} className="mt-5 grid gap-4"><div className="grid gap-4 sm:grid-cols-[180px_1fr]"><div className="space-y-1.5"><Label htmlFor="rating">Nota geral</Label><Input id="rating" required type="number" min="1" max="5" value={debrief.rating || (campaign.rating ? String(campaign.rating) : "")} onChange={event => setDebrief({ ...debrief, rating: event.target.value })} placeholder="1 a 5" /><p className="text-[11px] text-muted-foreground">1 = muito ruim · 5 = excelente</p></div><div className="space-y-1.5"><Label htmlFor="feedback">Avaliação e aprendizados</Label><Textarea id="feedback" required value={debrief.feedback || campaign.feedback || ""} onChange={event => setDebrief({ ...debrief, feedback: event.target.value })} placeholder="Resultados alcançados, aprendizados e próximos ajustes." className="min-h-28" /></div></div><label className="flex items-center gap-2 rounded-xl bg-secondary p-3 text-sm text-foreground"><input type="checkbox" checked={debrief.resultAchieved} onChange={event => setDebrief({ ...debrief, resultAchieved: event.target.checked })} className="h-4 w-4 accent-primary" />Objetivo da veiculação foi atingido</label>{canWrite && <Button type="submit" disabled={saveDebrief.isPending} className="justify-self-end">{saveDebrief.isPending ? "Salvando..." : "Salvar debriefing"}</Button>}</form></article></section>
      <aside className="space-y-5"><article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><FileImage className="h-4 w-4 text-primary" /><div><p className="font-display text-lg font-semibold text-foreground">Evidências</p><p className="text-xs text-muted-foreground">Fotos e documentos da veiculação.</p></div></div><div className="mt-4 grid grid-cols-2 gap-2">{campaign.evidences.map(evidence => <a key={evidence.id} href={evidence.url} target="_blank" rel="noreferrer" className="group relative min-h-24 overflow-hidden rounded-xl border border-border bg-secondary p-3"><FileImage className="h-5 w-5 text-primary" /><p className="mt-3 line-clamp-2 text-xs font-medium text-foreground">{evidence.originalName}</p><ExternalLink className="absolute right-2 top-2 h-3.5 w-3.5 text-muted-foreground" /></a>)}</div>{!campaign.evidences.length && <p className="mt-4 rounded-xl bg-secondary p-3 text-sm text-muted-foreground">Nenhuma evidência cadastrada ainda.</p>}<div className="mt-4"><EvidenceUpload entityType="media_campaign" entityId={campaign.id} canWrite={canWrite} /></div></article><article className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-primary" /><div><p className="font-display text-lg font-semibold text-foreground">Histórico</p><p className="text-xs text-muted-foreground">Alterações e movimentos mais recentes.</p></div></div><div className="mt-4 space-y-3">{campaign.history.length ? campaign.history.map(entry => <div key={entry.id} className="border-l-2 border-primary/30 pl-3"><p className="text-xs font-medium text-foreground">{entry.action === "schedule" ? "Veiculação planejada" : entry.action === "reschedule" ? "Veiculação reagendada" : entry.action === "save_debrief" ? "Debriefing atualizado" : entry.action.startsWith("status_") ? `Status alterado para ${statusLabels[entry.action.replace("status_", "")]}` : "Atualização registrada"}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{new Date(entry.occurredAt).toLocaleString("pt-BR")}</p></div>) : <p className="text-sm text-muted-foreground">Ainda não há eventos no histórico.</p>}</div></article></aside></div>
    <Dialog open={reasonOpen} onOpenChange={setReasonOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Cancelar veiculação</DialogTitle><DialogDescription>Registre o motivo do cancelamento. O histórico ficará disponível na ficha da veiculação.</DialogDescription></DialogHeader><div className="space-y-3"><Label htmlFor="cancel-reason">Motivo</Label><Textarea id="cancel-reason" value={reason} onChange={event => setReason(event.target.value)} placeholder="Informe a justificativa do cancelamento." /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setReasonOpen(false)}>Voltar</Button><Button type="button" variant="destructive" disabled={!reason.trim() || updateStatus.isPending} onClick={() => updateStatus.mutate({ campaignId, status: "cancelled", reason })}>Cancelar veiculação</Button></div></div></DialogContent></Dialog>
    <Dialog open={renewalOpen} onOpenChange={setRenewalOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Reagendar veiculação</DialogTitle><DialogDescription>Uma nova veiculação será criada e a atual será encerrada, preservando o vínculo com a mídia registrada.</DialogDescription></DialogHeader><form onSubmit={submitRenewal} className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="renewal-name">Nome</Label><Input id="renewal-name" required value={renewal.name} onChange={event => setRenewal({ ...renewal, name: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="renewal-start">Novo início</Label><Input id="renewal-start" required type="date" value={renewal.startsOn} onChange={event => setRenewal({ ...renewal, startsOn: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="renewal-end">Novo fim</Label><Input id="renewal-end" required type="date" value={renewal.endsOn} onChange={event => setRenewal({ ...renewal, endsOn: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="renewal-value">Valor</Label><Input id="renewal-value" type="number" min="0" step="0.01" value={renewal.estimatedCost} onChange={event => setRenewal({ ...renewal, estimatedCost: event.target.value })} /></div><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="renewal-reason">Motivo do reagendamento</Label><Textarea id="renewal-reason" required value={renewal.reason} onChange={event => setRenewal({ ...renewal, reason: event.target.value })} placeholder="Explique a necessidade do reagendamento." /></div><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={() => setRenewalOpen(false)}>Cancelar</Button><Button type="submit" disabled={renew.isPending}>{renew.isPending ? "Reagendando..." : "Confirmar reagendamento"}</Button></div></form></DialogContent></Dialog>
  </main>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-secondary p-3"><p className="text-[11px] font-semibold uppercase tracking-[.1em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium text-foreground">{value}</p></div>; }
