import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { MapPin } from "lucide-react";
import { useMemo, useState } from "react";

export default function MediaCoverageExplorer() {
  const reference = trpc.media.referenceData.useQuery(); const [regionalId, setRegionalId] = useState(""); const [cityId, setCityId] = useState("");
  const input = useMemo(() => ({ regionalId: regionalId ? Number(regionalId) : undefined, cityId: cityId ? Number(cityId) : undefined }), [regionalId, cityId]); const points = trpc.media.list.useQuery(input); const cities = reference.data?.cities.filter(item => !regionalId || item.city.regionalId === Number(regionalId)) ?? [];
  return <section className="mx-auto mt-6 max-w-[1480px] rounded-2xl border border-[#dbe6e3] bg-white p-5 shadow-[0_3px_12px_rgba(24,48,43,0.025)]"><div><p className="font-display text-base font-semibold text-[#304842]">Explorador de cobertura territorial</p><p className="mt-0.5 text-xs text-[#74857e]">Filtre pontos de mídia por regional e cidade para organizar a cobertura contratada.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><Label htmlFor="coverage-regional">Regional</Label><select id="coverage-regional" value={regionalId} onChange={event => { setRegionalId(event.target.value); setCityId(""); }} className="mt-1.5 h-9 w-full rounded-md border border-input bg-white px-3 text-sm"><option value="">Todas as regionais</option>{reference.data?.regionals.map(regional => <option key={regional.id} value={regional.id}>{regional.name}</option>)}</select></div><div><Label htmlFor="coverage-city">Cidade</Label><select id="coverage-city" value={cityId} onChange={event => setCityId(event.target.value)} className="mt-1.5 h-9 w-full rounded-md border border-input bg-white px-3 text-sm"><option value="">Todas as cidades</option>{cities.map(({ city }) => <option key={city.id} value={city.id}>{city.name} · {city.state}</option>)}</select></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{points.data?.length ? points.data.map(point => <div key={point.id} className="rounded-xl bg-[#f7faf8] p-3"><p className="text-xs font-semibold text-[#36554e]">{point.name}</p><p className="mt-1 text-[11px] text-[#76877f]">{point.regionalName} · {point.cityName}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-[#82928d]"><MapPin className="h-3 w-3" />{point.address || "Sem endereço"}</p></div>) : <p className="col-span-full py-3 text-xs text-[#89968f]">Não há pontos para os filtros selecionados.</p>}</div></section>;
}
