import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Check, ChevronsUpDown, Search } from "lucide-react";
import { useMemo, useState } from "react";

export type SelectableOption = { id: number; label: string; description?: string };

export default function SearchableMultiSelect({ id, label, options, values, onChange, disabled = false, placeholder = "Selecionar itens", emptyMessage = "Nenhuma opção disponível", maxSelections, hideLabel = false, triggerClassName = "", contentClassName = "" }: { id: string; label: string; options: SelectableOption[]; values: number[]; onChange: (values: number[]) => void; disabled?: boolean; placeholder?: string; emptyMessage?: string; maxSelections?: number; hideLabel?: boolean; triggerClassName?: string; contentClassName?: string }) {
  const [search, setSearch] = useState("");
  const available = useMemo(() => options.filter(option => `${option.label} ${option.description ?? ""}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))), [options, search]);
  const selectedLabels = options.filter(option => values.includes(option.id)).map(option => option.label);
  const toggle = (idToToggle: number) => onChange(values.includes(idToToggle) ? values.filter(value => value !== idToToggle) : maxSelections === 1 ? [idToToggle] : [...values, idToToggle]);
  return <div className="grid gap-1.5">{!hideLabel && <Label htmlFor={id}>{label}</Label>}<Popover><PopoverTrigger asChild><Button id={id} aria-label={label} type="button" variant="outline" disabled={disabled} className={`h-10 w-full justify-between rounded-lg px-3 text-left font-normal ${triggerClassName}`}><span className="truncate">{selectedLabels.length ? `${selectedLabels.length} selecionado${selectedLabels.length > 1 ? "s" : ""}: ${selectedLabels.slice(0, 2).join(", ")}${selectedLabels.length > 2 ? "…" : ""}` : placeholder}</span><ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-55" /></Button></PopoverTrigger><PopoverContent align="start" className={`w-[min(24rem,calc(100vw-2rem))] p-3 ${contentClassName}`}><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input autoFocus value={search} onChange={event => setSearch(event.target.value)} placeholder="Pesquisar…" className="h-9 pl-9" /></div><div className="mt-2 max-h-60 touch-pan-y overflow-y-auto overscroll-contain rounded-lg border border-border p-1" onWheelCapture={event => event.stopPropagation()}>{available.length ? available.map(option => <label key={option.id} className="flex cursor-pointer items-start gap-2 rounded-md px-2 py-2 text-sm hover:bg-muted"><Checkbox checked={values.includes(option.id)} onCheckedChange={() => toggle(option.id)} aria-label={`Selecionar ${option.label}`} /><span className="min-w-0"><span className="block truncate text-foreground">{option.label}</span>{option.description && <span className="block truncate text-xs text-muted-foreground">{option.description}</span>}</span>{values.includes(option.id) && <Check className="ml-auto mt-0.5 h-3.5 w-3.5 text-primary" />}</label>) : <p className="px-2 py-5 text-center text-xs text-muted-foreground">{emptyMessage}</p>}</div>{values.length > 0 && <Button type="button" variant="ghost" size="sm" onClick={() => onChange([])} className="mt-2 h-7 px-2 text-xs">Limpar seleção</Button>}</PopoverContent></Popover></div>;
}
